name: Build Win-wheels for PQMagic-Python

on:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2022]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        architecture: [x64]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}
    
    - name: Install build tools
      shell: pwsh
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel Cython
        choco install cmake --yes --no-progress
        choco install mingw --yes --no-progress
        echo "C:\ProgramData\chocolatey\bin" | Out-File -FilePath $env:GITHUB_PATH -Append
        echo "C:\tools\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Append

    - name: Build win wheels
      run: python3 setup.py bdist_wheel

    # Error: ModuleNotFound. Weirdly, these tests work locally but not in the CI environment.
    #- name: Test the wheel locally
    #  run: |
    #    python -m pip install dist/*.whl
    #    python -c "import pqmagic; print(pqmagic.__version__)"
    #    python -c "from pqmagic import Kem; from binascii import hexlify; kem = Kem('ML_KEM_512'); pk, sk = kem.keygen(); print(hexlify(pk).decode('utf-8')); print('\n'); print(hexlify(sk).decode('utf-8'))"
    #    python tests/pypqmagic_kem_tests.py
    #    python tests/pypqmagic_sig_tests.py

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ matrix.os }}-py${{ matrix.python-version }}
        path: dist/*